const data = [
    {
      id: 1,
      name: 'Rambo',
      image: 'https://swarajya.gumlet.io/swarajya/2020-02/31e433d0-1384-450a-8d51-04da6e95f412/Combai.jpg?w=732&q=75&compress=true&format=auto', 
      age: 3,
      vaccinated: 'yes',
      size: 'medium',
      breed: 'Kombai',
      temperament: 'Friendly and Energetic',
      medicalHistory: 'No known issues',
      previousHome: 'Rescued from a shelter',
      favoriteActivities: 'Playing fetch',
      microchipStatus: 'Yes'
    },
    {
      id: 2,
      name: 'Buddy',
      image: 'https://nativepet.com/cdn/shop/articles/German-Shepherd-lying-on-the-grass.jpg?v=1663566238&width=1000', 
      age: 5,
      vaccinated: 'no',
      size: 'large',
      breed: 'German Shepherd',
      temperament: 'Loyal and Protective',
      medicalHistory: 'Hip dysplasia',
      previousHome: 'Owner moved away',
      favoriteActivities: 'Running',
      microchipStatus: 'No'
    },
    {
      id: 3,
      name: 'Bella',
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCTfiEqp81NykEa368QIw7x89LOhrJEhWzFw&s', 
      age: 2,
      vaccinated: 'yes',
      size: 'small',
      breed: 'Beagle',
      temperament: 'Curious and Playful',
      medicalHistory: 'No known issues',
      previousHome: 'Found as a stray',
      favoriteActivities: 'Sniffing around',
      microchipStatus: 'Yes'
    },
    {
      id: 4,
      name: 'Max',
      image: 'https://www.chow-bella.co.uk/cdn/shop/articles/a-deep-dive-into-cocker-spaniel-health-spotting-common-conditions-and-ensuring-optimal-care-804457.jpg?v=1691565414', 
      age: 4,
      vaccinated: 'yes',
      size: 'medium',
      breed: 'Cocker Spaniel',
      temperament: 'Affectionate and Gentle',
      medicalHistory: 'No known issues',
      previousHome: 'Owner passed away',
      favoriteActivities: 'Cuddling',
      microchipStatus: 'No'
    },
    {
      id: 5,
      name: 'Luna',
      image: 'https://www.dogster.com/wp-content/uploads/2024/03/teacup-pomeranian-running-on-grass_thanai-asawaroengchai-Shutterstock_512443759.webp', 
      age: 1,
      vaccinated: 'no',
      size: 'small',
      breed: 'Pomeranian',
      temperament: 'Energetic and Alert',
      medicalHistory: 'No known issues',
      previousHome: 'Surrendered by previous owner',
      favoriteActivities: 'Playing with toys',
      microchipStatus: 'Yes'
    },
    {
      id: 6,
      name: 'Rocky',
      image: 'https://cdn.britannica.com/46/233846-050-8D30A43B/Boxer-dog.jpg', 
      age: 6,
      vaccinated: 'yes',
      size: 'large',
      breed: 'Boxer',
      temperament: 'Friendly and Confident',
      medicalHistory: 'Allergies',
      previousHome: 'Rescued from abuse',
      favoriteActivities: 'Running and playing',
      microchipStatus: 'No'
    },
    {
      id: 7,
      name: 'Daisy',
      image: 'https://img.etimg.com/thumb/width-420,height-315,imgsize-29028,resizemode-75,msid-104863570/news/international/uk/american-xl-bully-dog-breed-banned-in-uk-and-wales/american-xl-bully-dog-shot-in-uk-owner-arrested-know-incident-in-which-man-was-killed.jpg', 
      age: 3,
      vaccinated: 'yes',
      size: 'medium',
      breed: 'Bulldog',
      temperament: 'Loving and Calm',
      medicalHistory: 'No known issues',
      previousHome: 'Given up by owner',
      favoriteActivities: 'Relaxing',
      microchipStatus: 'Yes'
    },
    {
      id: 8,
      name: 'Sadie',
      image: 'https://cdn.royalcanin-weshare-online.io/CFbj63oBBKJuub5qVbmX/v3/bp-lot-2-chihuahua-long-colour-human', 
      age: 4,
      vaccinated: 'no',
      size: 'small',
      breed: 'Chihuahua',
      temperament: 'Alert and Affectionate',
      medicalHistory: 'Dental issues',
      previousHome: 'Found abandoned',
      favoriteActivities: 'Being held',
      microchipStatus: 'No'
    },
    {
      id: 9,
      name: 'Toby',
      image: 'https://media-be.chewy.com/wp-content/uploads/2021/05/13111557/GettyImages-1467947700-923x615.jpg', 
      age: 5,
      vaccinated: 'yes',
      size: 'medium',
      breed: 'Shih Tzu',
      temperament: 'Gentle and Loving',
      medicalHistory: 'No known issues',
      previousHome: 'Owner relocated',
      favoriteActivities: 'Playing with balls',
      microchipStatus: 'Yes'
    },
    {
      id: 10,
      name: 'Charlie',
      image: 'https://media.istockphoto.com/id/1971124912/photo/golden.webp?b=1&s=612x612&w=0&k=20&c=-u-KLUrBXhHb5VPc5fu7XjGsu8EVurw5to9JlYrudfM=', 
      age: 2,
      vaccinated: 'no',
      size: 'large',
      breed: 'Golden Retriever',
      temperament: 'Friendly and Playful',
      medicalHistory: 'No known issues',
      previousHome: 'Rescued from a puppy mill',
      favoriteActivities: 'Running and fetching',
      microchipStatus: 'No'
    },
    {
      id: 11,
      name: 'Maggie',
      image: 'https://cdn.britannica.com/22/234622-050-4D6BD081/Australian-shepherd-dog-red-merle.jpg', 
      age: 3,
      vaccinated: 'yes',
      size: 'medium',
      breed: 'Australian Shepherd',
      temperament: 'Intelligent and Energetic',
      medicalHistory: 'No known issues',
      previousHome: 'Owner passed away',
      favoriteActivities: 'Herding',
      microchipStatus: 'Yes'
    },
    {
      id: 12,
      name: 'Jack',
      image: 'https://media-be.chewy.com/wp-content/uploads/2021/06/02102805/Doberman-Pinscher_Featured-Image.jpg', 
      age: 3,
      vaccinated: 'no',
      size: 'large',
      breed: 'Doberman',
      temperament: 'Loyal and Protective',
      medicalHistory: 'No known issues',
      previousHome: 'Surrendered due to move',
      favoriteActivities: 'Guarding',
      microchipStatus: 'No'
    }
  ];

  export default data;